### PR TITLE
Add embedded stream preview

### PR DESCRIPTION
**Pull request by danielfspencer**
This PR adds an embedded view of the livestream to the main page to increase immediate visibility of activity during the event. The stream is only shown when it is live, it is hidden the rest of the time. The title of the current event is displayed above the stream.  

Not yet ready for merge. Outstanding issues:
- On small devices, the background image is not tall enough to read the chequered line when the stream is present
- On small devices, the spacing between the main logo/buttons and the stream is not enough
- Clicking the stream should open twitch but it does not

No stream:
(exactly the same as before)

Stream live (large device):
Screen Shot 2020-03-19 at 21 55 12

Stream live (small device portrait):
image

Stream live (small device landscape):
Screen Shot 2020-03-19 at 21 55 41

### CODE REVIEW

**Comment by tomMisson** [comment]
Dude this is amazing!!!

**Comment by danielfspencer** [comment]
Remaining issues:
- Clicking stream does not take you to twitch
- Layout for small devices is not great

**Comment by danielfspencer** [comment]
- Added upcoming events calendar (shown when no event is live)
- Improved small screen layout
Screen Shot 2020-03-21 at 00 48 38
Screen Shot 2020-03-21 at 00 48 20

**Comment by danielfspencer** [comment]
Clicking the stream takes you to Twitch, and clicking the calendar takes you to the full calendar now. Marking as ready for review.

**Review by bahorn — APPROVED** [review]

**Comment by bahorn** [comment]
All seems good, can't test with a stream so i'll trust your judgement :)

**Pull request merged**
