### PR TITLE
Replace submit wokrshop to submit project

### PR DESCRIPTION
**Pull request by wrussell1999**

### CODE REVIEW

**Comment by wrussell1999** [comment]
Wait a second, I never finished the `/submissions` page

**Review by tomMisson — APPROVED** [review]
Looks good friendo

**Comment by wrussell1999** [comment]
Dude, did you read my comment! It doesn't work xD

**Comment by tomMisson** [comment]
I was reviewing while you commented... Hang on and I can re-review

**Comment by wrussell1999** [comment]
You clearly didn't review it because the buttons don't work xD

**Comment by tomMisson** [comment]
Sorry 😢

**Comment by wrussell1999** [comment]
It's all good dude, have a play around in the Netlify preview to make sure all is good :D Mostly because I forgot to finish a file doh!

**Comment by tomMisson** [comment]
I can't seem to see the checks in the app... Am I right in saying they don't show up?

**Comment by wrussell1999** [comment]
I also can't type ....oops

**Comment by wrussell1999** [comment]
Yeah the app is limiting. I'd recommend using the website to get the netlify deploy preview

**Comment by tomMisson** [comment]
Will do, thanks mate

**Pull request merged**
