### PR TITLE
Remove duplicate side events on schedule

### PR DESCRIPTION
**Pull request by tomMisson**

### CODE REVIEW

**Review by danielfspencer — CHANGES_REQUESTED** [review]
This breaks highlighting of non-streamed side events
image
(town of salem should be grey)

**Review by tomMisson — COMMENTED** [review]
That should sort it @danielfspencer

**Comment by tomMisson** [comment]
Ah so now there is a grey spec that appears at the top but no text in it.... Is there a different way to sort it that what I am proposing or do we scrap the idea and live with a duplicate?

**Comment by danielfspencer** [comment]
I'd prefer it if all events were colour coded. To remove the spec at the top, you could add another field to the event_colours.yml file that optionally hides a label? Or maybe hide all labels that have empty names? Either way, the Liquid that processes the yml is found in both schedule.md and upcoming.md

**Comment by danielfspencer** [comment]
Fixed in #123

**Pull request closed without merging**
