### PR TITLE
Change St Andrews logo

### PR DESCRIPTION
**Pull request by tomMisson**

### CODE REVIEW

**Comment by ksouthern** [comment]
Is there a way to remove the thick white border from around it?

**Comment by tomMisson** [comment]
Removed the styling from the previous image, should be sorted now!

**Comment by ksouthern** [comment]
not a great sign :/

**Comment by tomMisson** [comment]
I have no idea why its failing, Netflify logs say system error and Jekyll build CI says missing SSH key but I have no key or idea why key it wants, the code changes are minor and don't affect any Jekyll templates @bahorn any ideas with this?

**Comment by danielfspencer** [comment]
No idea why netlify gave up. Is this logo really an improvement?
image
Should I try to add a black border and make it bigger?

**Comment by danielfspencer** [comment]
Re: the netlify issue
It might not be able to make a preview when the branch is from a different repo? In the future make a branch on this repo then PR.

**Pull request closed without merging**
